#!/bin/sh

set -e

case $1 in
install | upgrade)
	# workaround command-with-path-in-maintainer-script for /usr/bin
	conflicts="
/usr/lib/xorg/modules/libglamoregl.so /usr/bin/sddm-greeter-qt6
/usr/bin/plasma-discover
/usr/lib/xorg/modules/drivers/modesetting_drv.so /usr/bin/Xorg
/usr/share/wayland-sessions/plasma.desktop
"
	for i in $conflicts; do
		dpkg-divert --package xserver-xorg-img-bxm-1.21.1-2.deb --divert "$i.bak" --rename "$i"
	done
	;;
esac

#DEBHELPER#

exit 0
