#!/bin/sh

set -e

#DEBHELPER#

case $1 in
remove)
	# workaround command-with-path-in-maintainer-script for /usr/bin
	conflicts="
/usr/lib/xorg/modules/libglamoregl.so /usr/bin/sddm-greeter-qt6
/usr/bin/plasma-discover
/usr/lib/xorg/modules/drivers/modesetting_drv.so /usr/bin/Xorg
/usr/share/wayland-sessions/plasma.desktop
"
	for i in $conflicts; do
		dpkg-divert --package xserver-xorg-img-bxm-1.21.1-2.deb --rename --remove "$i"
	done
	;;
esac

exit 0
